language: node_js
node_js:
  - 10
sudo: required

services:
  - docker

before_install:
  - docker build -t yogeshnm/my-react-app -f Dockerfile.dev .
  - docker run -e CI=true yogeshnm/my-react-app npm run test

script:
  - docker run -e CI=true yogeshnm/my-react-app npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "yn-react-app"
  env: "YnReactApp-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-782026352736"
  bucket_path: "my-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
