sudo: required
services:
  - docker

before_install:
  - docker build -t yogeshnm/my-react-app -f Dockerfile.dev .
  - docker run -e CI=true yogeshnm/my-react-app npm run test

script:
  - docker run -e CI=true yogeshnm/my-react-app npm run test -- --coverage